version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.31
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USERNAME=app
      - MYSQL_PASSWORD=pass
    ports:
      - '3306:3306'
  mypostgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
  node-app:
    build: ./artifacts/gate-simulator/
    ports:
      - '9999:9999'